
name: configure-dev-machine
version: REPLACE_VERSION
description: |
  Internal tools for developers in Altipla Consulting.

arch: amd64
platform: linux

section: default
priority: extra
provides:
- configure-dev-machine

maintainer: Altipla Consulting <ernesto@altiplaconsulting.com>
vendor: Altipla Consulting
homepage: https://github.com/altipla-consulting/tools
license: MIT

contents:
- src: ./configure-dev-machine
  dst: /usr/local/bin/configure-dev-machine
