
name: previewer-netlify
version: REPLACE_VERSION
description: |
  Internal tools for developers in Altipla Consulting.

arch: amd64
platform: linux

section: default
priority: extra
provides:
- previewer-netlify

maintainer: Altipla Consulting <ernesto@altiplaconsulting.com>
vendor: Altipla Consulting
homepage: https://github.com/altipla-consulting/tools
license: MIT

contents:
- src: ./previewer-netlify
  dst: /usr/local/bin/previewer-netlify
