
on: 
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Configure Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3

    - name: Release ci
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/ci
        name: ci

    - name: Release gaestage
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/gaestage
        name: gaestage

    - name: Release gendc
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/gendc
        name: gendc

    - name: Release impsort
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/impsort
        name: impsort

    - name: Release jnet
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/jnet
        name: jnet

    - name: Release linter
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/linter
        name: linter

    - name: Release previewer-netlify
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/previewer-netlify
        name: previewer-netlify

    - name: Release pub
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/pub
        name: pub

    - name: Release reloader
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/reloader
        name: reloader

    - name: Release wave
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/wave
        name: wave

    - name: Release releaser
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/releaser
        name: releaser
