
on: 
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Get the version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: altipla-tools

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@main
      with:
        workload_identity_provider: projects/1060593636030/locations/global/workloadIdentityPools/github/providers/github
        service_account: gha-tools@precise-truck-89123.iam.gserviceaccount.com
        create_credentials_file: true
    - name: Login to Google Cloud
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

    - name: Release ci
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/ci
        name: ci

    - name: Release gaestage
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/gaestage
        name: gaestage

    - name: Release gendc
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/gendc
        name: gendc

    - name: Release impsort
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/impsort
        name: impsort

    - name: Release jnet
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/jnet
        name: jnet

    - name: Release linter
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/linter
        name: linter

    - name: Release previewer-netlify
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/previewer-netlify
        name: previewer-netlify

    - name: Release pub
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/pub
        name: pub

    - name: Release reloader
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/reloader
        name: reloader

    - name: Release wave
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/wave
        name: wave

    - name: Release releaser
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/releaser
        name: releaser

    - name: Release configure-dev-machine
      uses: altipla-consulting/go-release.actions@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ./cmd/configure-dev-machine
        name: configure-dev-machine

    - name: Release install scripts
      run: |-
        gcloud --quiet components install alpha
        sed -i 's/REPLACE_VERSION/${{ steps.version.outputs.VERSION }}/g' install/configure-dev-machine
        gcloud alpha storage cp -R install gs://tools.altipla.consulting
